name: Node.js Test

on:
  workflow_dispatch:

jobs:
  Node_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
      
      - name: Setup Node.js
        uses: actions/setup-node
        with:
          node-version: '20.x'
        
      - name: Run tests
        run: npm test
